### Login
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "clinton",
    "password": "123"
}

### Create Volunteer
POST http://localhost:8080/users
Content-Type: application/json

{
    "username": "arshhjgjia",
    "password": "gh123",
    "email": "gholamjhgi@email.com",
    "fullname": "arshia gh",
    "phoneNo": "kjjghhj",
    "type": "Volunteer",
    "occupation": "jg",
    "dob": "2002-06-20"
}

### Create SchoolAdmin
POST http://localhost:8080/schools/637cb631cf5b437c245d5738/admins
Content-Type: application/json

{
    "username": "clinton",
    "password": "123",
    "email": "admin@email.com",
    "fullname": "clinton",
    "phoneNo": "+60 100200",
    "position": "IT Support",
    "staffId": "GG100"
}

### Create School
POST http://localhost:8080/schools
Content-Type: application/json

{
    "name": "HELP University",
    "address": {
        "city": "Shah Alam",
        "state": "Selangor",
        "street": "lorem"
    }
}

### Find School by ID
GET http://localhost:8080/schools/6359db5f688aabd13eee7129
Content-Type: application/json

### Update User Profile
PATCH http://localhost:8080/users/arsh
Content-Type: application/json

{
    "staffId": "hello world"
}

### Get Admins of a School

GET http://localhost:8080/schools/6359db5f688aabd13eee7129/admins
Content-Type: application/json

### Get Requests of a School
GET http://localhost:8080/schools/6359db5f688aabd13eee7129/requests
Content-Type: application/json

### Create Request
POST http://localhost:8080/schools/637cb631cf5b437c245d5738/requests
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2U0OTM2YzA4MjlkYWRlZTlkZTA4YyIsInVzZXJuYW1lIjoiY2xpbnRvbiIsInR5cGUiOiJTY2hvb2xBZG1pbiIsImlhdCI6MTY2OTIyMDcwN30.4y4YysDgpc-p5A7nunkQYkm48R574BQpMWuUgg0wyDk

{
    "title": "test",
    "description": "test description",
    "numRequired": 25,
    "type": "Resource",
    "resourceType": "MobileDevice"
}

### Get All Requests
GET http://localhost:8080/requests
Content-Type: application/json

### Find Request by Id

GET http://localhost:8080/requests/637cbfa85e467ea06480fcdb
Content-Type: application/json

### Create Offer

POST http://localhost:8080/requests/637cbfa85e467ea06480fcdb/offers
Content-Type: application/json

{
    "remarks": "Hello World"
}

### Accept Offer

PUT http://localhost:8080/requests/637cbfa85e467ea06480fcdb/offers/637ce415caa1167cae2ea8ce/accept
Content-Type: application/json
